@startuml UC7-Login

skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam backgroundColor transparent
skinparam style strictuml

package Nuxt {
    class $router <<domain>> {
        --
        + push(path) : void
    }

    class $store <<domain>> {
        + state : object
        --
        + commit(type, payload, options) : Promise
        + dispatch(type, payload) : Promise
    }
}

class login <<controller>> {
    - waiting() : bool
    - login() : void
}
login-->$store

class auth <<domain>> {
    + token : string <<get, set>>
    + error : string <<get, set>>
    + user : object <<get, set>>
    --
    + attemptLogin() : void <<action>>
    + AuthToken(state, token) : void <<mutation>>
    + AuthUser(state, info) : void <<mutation>>
    + AuthError(state, error) : void <<mutation>>
}
$store ---> auth
auth --> $router

class api <<boundary>> {
    --
    + attemptLogin(info) : Promise
}
auth --> api

class localStorage <<boundary>> {
    --
    + setItem(key, value) : void
}
auth --> localStorage

class axios <<boundary>> {
    --
    + post(url, data, config) : Promise
}
api -> axios

@enduml
