@startuml UC8-Logout

skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam backgroundColor transparent
skinparam style strictuml



package Nuxt {
    class $router <<domain>> {
        + currentRoute
        --
        + push(path) : void
    }

    class $store <<domain>> {
        + state : object
        --
        + commit(type, payload, options) : Promise
        + dispatch(type, payload) : Promise
    }
}

class header <<controller>> {
    --
    - logout() : void
}
header-->$store

class auth <<domain>> {
    + token : string <<get, set>>
    + user : object <<get, set>>
    --
    + logout() : void <<action>>
    + AuthToken(state, token) : void <<mutation>>
    + AuthUser(state, info) : void <<mutation>>
}
$store ---> auth
auth --> $router

class localStorage <<boundary>> {
    --
    + clear() : void
}
auth --> localStorage

@enduml
